export enum ErrorCodesEnum {
	AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
	AUTH_ACCESS_TOKEN_CIPRATION_ERROR = 'AUTH_ACCESS_TOKEN_CIPRATION_ERROR',
	AUTH_REFRESH_TOKEN_CIPRATION_ERROR = 'AUTH_REFRESH_TOKEN_CIPRATION_ERROR',
	AUTH_PASSWORD_CIPRATION_ERROR = 'AUTH_PASSWORD_CIPRATION_ERROR',
	AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
	REPOSITORY_ERROR = 'REPOSITORY_ERROR',
	USERS_EMAIL_ALREADY_REGISTERED = 'USERS_EMAIL_ALREADY_REGISTERED',
	USERS_NOT_FOUND = 'USERS_NOT_FOUND',
}

export type ErrorCodes = typeof ErrorCodesEnum;
